name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - name: Analysing the code with ruff
      run: |
        ruff check --select ERA,ANN,S,BLE,FBT,B,A,COM,C4,DTZ,T10,EM,FIX,FA,INT,ISC,ICN,LOG,INP,PIE,T20,PT,Q,RSE,RET,SLF,SIM,TID,TD,ARG,PTH,I,N,E,F,RUF $(git ls-files '*.py')
